const Config = {
  PROJECT_URL: secrets.PROJECT_URL,
  PROJECT_SAVE_URL: secrets.PROJECT_SAVE_URL,
  AWS_S3_BUCKET_NAME: secrets.AWS_S3_BUCKET_NAME,
  AWS_S3_REGION: secrets.AWS_S3_REGION,
  AWS_ACCESS_KEY_ID: secrets.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: secrets.AWS_SECRET_ACCESS_KEY,

  API_KEY: secrets.API_KEY,
};

export default Config;
