const Config = {
  PROJECT_URL: process.env.NEXT_PUBLIC_PROJECT_URL,
  PROJECT_SAVE_URL: process.env.NEXT_PUBLIC_PROJECT_SAVE_URL,
  AWS_S3_BUCKET_NAME: process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME,
  AWS_S3_REGION: process.env.NEXT_PUBLIC_AWS_S3_REGION,
  AWS_ACCESS_KEY_ID: process.env.NEXT_PUBLIC_AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY,

  API_KEY: process.env.API_KEY,
};

export default Config;
